### ISSUE TITLE
silently install different Setup Configurations

### ISSUE THREAD

**Issue by makotia** [dblock/dotnetinstaller#104]
Hello, is there a way to install different setup configurations silently?
Right now I have 5 different setup configurations in one config (as a drop-down menu). I have to break them up into 5 different configs in order to install silently.

I would love to have a silent command that I can specify for a specific setup config to install.

thank you

**Comment by icnocop** [comment]
Is this the same as https://github.com/dblock/dotnetinstaller/issues/83 ?

**Comment by makotia** [comment]
Yes...

**Comment by dblock** [comment]
Closing in favor of #83.
