### ISSUE TITLE
How to pass trade mark sign?

### ISSUE THREAD

**Issue by makotia** [dblock/dotnetinstaller#106]
Hello,
I am trying to pass &trade; to the .xml file but it doesn't seem to work, is there another char that I can reference to replace ™?

thank you

**Comment by icnocop** [comment]
Have you tried using `&#8482;` instead of `™`?

**Comment by makotia** [comment]
I just tried it, DNI says invalid character...

e.g. Microsoft&#8482;
exeparameters="&quotMicrosoft&#8482; Office&quot;

**Comment by icnocop** [comment]
Maybe DNI is complaining about `&quot` which should actually be `&quot;`.

**Comment by dblock** [comment]
This should be reproducible in a test, @makotia if you write one I could help fix it.
