### ISSUE TITLE
Add support for Windows 10 in os_filter_min, os_filter_max, and displayed appropriately in the main install bootstrapper dialog

### ISSUE THREAD

**Issue by icnocop** [dblock/dotnetinstaller#86]
Add support for Windows 10 in os_filter_min, os_filter_max, and displayed appropriately in the main install bootstrapper dialog.

For example,

1. os_filter_min should allow win10
2. os_filter_max should allow win10Max
3. "Windows 10 (x64)" should be displayed instead of what the main install bootstrapper dialog is displaying now: "Windows 8 (x64)".

**Comment by dblock** [comment]
Closed via https://github.com/dblock/dotnetinstaller/pull/87.

**Comment by dblock** [comment]
Btw README doesn't say that DNI supports Windows 10. It should.
