### ISSUE TITLE
exe properties and logo (icon) problem

### ISSUE THREAD

**Issue by vinogradniy** [dblock/dotnetinstaller#94]
dotNetInstaller 2.3-2.4

InstallerLinker.exe clear exe-properties and logo (icon) after embed cab.

Runs on:
 * Win8.1x64 - Properties and icon is empty 
 * Win2008R2x86 - Properties and the icon is present 

File properties image before and after embed cab: https://cloud.mail.ru/public/MK7F/aKmmxk3kH

**Comment by vinogradniy** [comment]
The problem can be reproduced only when viewing from the TotalCommander

**Comment by dblock** [comment]
So that screenshot isn't correct? That doesn't look like TotalCommander or what am I missing?

**Comment by vinogradniy** [comment]
Screenshot is correct.

It is likely to feature display properties of large files in tоtаlCоmmаnder. In Explorer all displayed correctly.


P.S. Bootstrapper file size > 300MB.

**Comment by dblock** [comment]
:+1: I've worked with 1.5GB bootstrappers, you'll be OK :)
